name: Unity Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI: ${{ secrets.OPENAI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-actions/setup@v2
        with:
          unityVersion: 2021.3.9f1  # 유니티 버전에 맞게 수정

      - name: Build project
        uses: game-ci/unity-actions/build@v2
        with:
          targetPlatform: StandaloneWindows64  # 또는 WebGL, Android 등

      - name: Use secret in script
        run: echo "Your OpenAI key is $OPENAI"
